# Generated by Django 2.0.1 on 2018-01-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='factor',
        ),
    ]
